# in this code we will learn the types of messages in Langchain
# there are basically 3 types of messages 1)System Message (SystemMessage) 2)Human Messag (HumanMessage) 3) AI Message (AIMessage)
# system message - it's the inetial message which we use to define the job of chatbot e.g. you are a helpful assistant, you are a professional doctor
# Human message - it's the question's asked by user or the message send by users
# AI Message - it's the message generated by AI or BOT

# this is a code to show how we can sotore the converstion.
# this is importent becasue - if we dont lable the coverstation and the conversation gets bigger the Bot won't
# be able to distinguse between it's own message and user message
# another exaple is chatbot_3.py

from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from langchain_google_genai import ChatGoogleGenerativeAI
from dotenv import load_dotenv

load_dotenv()

model = ChatGoogleGenerativeAI(model = "gemini-3.6-flash")

messages = [
    SystemMessage(content = 'You are a helpful assistant'), # job for bot
    HumanMessage(content = 'Tell me about langchian') # the user question
]

result = model.invoke(messages)

messages.append(AIMessage(content= result.content[0]["text"])) # adding ai result

print(messages)